(lang dune 3.19)

(name lichessserver)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Niklas Kirschall <niki.nice1203@gmail.com>")

(maintainers "Niklas Kirschall <niki.nice1203@gmail.com>")

(license LICENSE)

(documentation https://github.com/nkxxll/lichessauth.git)

(package
 (name lichessserver)
 (synopsis "Lichess OAuth2.0 study")
 (description
  "A lichess application that shows you where you went wrong in your opening from one or more course pgn files.")
 (depends
  ocaml
  cohttp
  cohttp-lwt-unix
  dream
  ocaml-base-compiler
  ppx_deriving
  ppx_deriving_yojson
  ppx_expect)
 (tags
  ("chess" "oauth" "expect test" "dream" "lwt")))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
